name: unit-tests

on:
  push:
    paths:
      - '.github/workflows/*'
      - 'lib/*'
      - 'test/*'
      - 'index.js'
      - 'package.json'

jobs:
  test:
    name: lib testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm test
